### ISSUE TITLE
Move hard-coded configuration options to environment variables

### ISSUE THREAD

**Issue by saulchristie** [MasterPhooey/Debrid-Search#1]
Would it be possible to remove the hard-coded values contained in the 'config' object at main.py line 52 and replace with values obtained from the env / docker-compose.yml via os.getenv as per your existing lines 47,48,49?

This would allow users to use this frontend with selfhosted Comet installs where your hard-coded indexers may not be defined, or debrid proxying is allowed etc. as well as enable easier configuration of what languages or resolutions are returned to a user.

**Comment by MasterPhooey** [comment]
updated!
